### ISSUE TITLE
update Project URL on Puppet Forge and changelog

### ISSUE THREAD

**Issue by cristianbalan-mf** [elastic/puppet-elastic-stack#1]
Could you please update the Project URL on https://forge.puppet.com/elastic/elastic_stack which currently points to https://github.com/jarpy/puppet-elastic-stack and it doesn't exist?
Could you also fill the changelog as is very useful to see how this project proceeds, please?

**Comment by jarpy** [comment]
Good points, thanks. Both of these are important items that were lost in the transition from prototype to production.
