### ISSUE TITLE
kibana packages not found in oss repository

### ISSUE THREAD

**Issue by DJMuggs** [elastic/puppet-elastic-stack#10]
Yum can't find the kibana packages in the https://artifacts.elastic.co/packages/oss-6.x/yum repository.

Yum can find the kibana packages in https://artifacts.elastic.co/packages/6.x/yum repository.

So when oss is set to true, kibana-oss package installation fails.

**Comment by jarpy** [comment]
Thanks (and sorry).

You've revealed a bug in Elastic's automated release process. With  the release of version 6.3.0, we published the OSS packages for Kibana to the wrong locations. I submitted a fix for our release automation which should fix the problem soon.

In the meantime, the RPM for OSS Kibana 6.3.0 can be found in the main repository at:

https://artifacts.elastic.co/packages/6.x/yum/6.3.0/kibana-oss-6.3.0-x86_64.rpm
