### ISSUE TITLE
Allow $version to set an specific release 

### ISSUE THREAD

**Issue by kamusin** [elastic/puppet-elastic-stack#13]
First of all, thank you for provide this functionality (although it has become now a requirement of the ES Module since version `6.3.0`). 

Previously in the ES Module we were able pin an specific release we wanted, such as for example:

```
elasticsearch::repo_version: '1.7.6'
```

now the suggestion from https://github.com/elastic/puppet-elasticsearch/issues/959, is to do something such as this:

```
elastic_stack::repo::version: 1.7.6
```

and you might expect this to work, but since this is not a valid Integer it will fail as you may expect:

```
Error: Evaluation Error: Error while evaluating a Function Call, Class[Elastic_stack::Repo]: parameter 'version' expects an Integer value, got Float
```

Can you please modify this parameter so that we can keep pinning specific releases (yes, it's an old release but hey, world is not perfect) without breaking the compatibility?  

For testing purposes, this is not specified on the README file, It seems like ES 1.x version is not supported either. On my `hiera` configuration I have set the following settings:

```
elasticsearch::version: '1.7.6'
elastic_stack::repo::version: 1
```

This is what you get:

```
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: W: The repository 'https://packages.elastic.co/elasticsearch/1.x/debian stable Release' does not have a Release file.
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: E: Failed to fetch https://packages.elastic.co/elasticsearch/1.x/debian/dists/stable/main/binary-amd64/Packages  404  Not Found
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: E: Some index files failed to download. They have been ignored, or old ones used instead.
Error: /Stage[main]/Apt::Update/Exec[apt_update]: Failed to call refresh: '/usr/bin/apt-get update' returned 100 instead of one of [0]
Error: /Stage[main]/Apt::Update/Exec[apt_update]: '/usr/bin/apt-get update' returned 100 instead of one of [0]
``` 

This is the resulting file with the repository  `/etc/apt/sources.list.d/elastic.list`:
```
deb https://packages.elastic.co/elasticsearch/1.x/debian stable main
```

PS: I'm running this under stack Ubuntu Xenial and Puppet module `6.3.0`

**Comment by jarpy** [comment]
This would need to be implemented in the Elasticsearch module, if it isn't already.

This module only deals with package repositories, which don't even have minor versions. They just have "5.x", "6.x" etc. Really, the line:

```
elasticsearch::repo_version: '1.7.6'
```
is quite strange. That should never have been called the "repo version", it is the "package version".

@tylerjl, @fatmcgav: do you have any suggestions for how this should be handled now?

**Comment by tylerjl** [comment]
So pulling this apart, I'm seeing a few questions:

- First, version 1 just isn't well-supported any more (it's very, truly dead from an end-of-life perspective), so I don't think you'll have much luck using `elastic_stack::repo` with v1 repositories - the module constructs repositories of the `"${major_version}.x"` form, and the 1.x series repositories looked like `1.7` instead.
- If you need to keep pinning elasticsearch versions, the `elasticsearch::version` parameter is still there for you - the Elasticsearch module delegates repo-level things to this module now, so there's no `repo_*`-level parameters to tinker with in that module.

Do let me know if I'm misunderstanding the intent here.

**Comment by kamusin** [comment]
@tylerjl yes, we can still pin the version with the `elasticsearch` module, however, there is no way to set a custom repository at the moment (we have to declare an Apt resource in the role for voiding this issue). 

I know, super old release..

**Comment by kamusin** [comment]
We are managing the repository by ourselves now, that worked around the issue for this ancient stack.
