### ISSUE TITLE
apt::update ordering creates dependency cycles

### ISSUE THREAD

**Issue by seocam** [elastic/puppet-elastic-stack#4]
This statement `Class['apt::update'] -> Package <| |>` [1] inserts a dependency in all packages defined not only by this module but for every other .pp file.

In many cases we want to install some packages *before* running the `apt::update` but this module makes in impossible. One example would be the package 'apt-transport-https'.

My suggestion is to only add the dependency to the specific packages the modules depends on instead of using the "wildcard".

[1] https://github.com/elastic/puppet-elastic-stack/blob/master/manifests/repo.pp#L34

**Comment by tylerjl** [comment]
As another datapoint, [this creates some dependency cycles when used in conjunction with the Kibana module](https://github.com/elastic/puppet-kibana/issues/18#issuecomment-349652292).

**Comment by jarpy** [comment]
Oh that's nasty. Thanks for pointing it out.

It saddens me that `apt-get update` is still not a solved problem in Puppet, but what I'm doing here is not helping!

**Comment by jarpy** [comment]
Perhaps we should remove this altogether. This module does not install any packages, so refreshing the package list is not really  its concern. Other modules that _do_ install packages will know the names of those packages, and thus what to order after the update resource.

**Comment by jarpy** [comment]
Fixed in version 6.0.1.

https://forge.puppet.com/elastic/elastic_stack/changelog#release-601
